# Generated by Django 5.2.7 on 2025-10-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
