# Generated by Django 5.2.7 on 2025-10-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='percent',
            field=models.FloatField(),
        ),
    ]
