# Generated by Django 5.2.7 on 2025-10-25 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Special Category',
                'verbose_name_plural': 'Special Categories',
            },
        ),
        migrations.CreateModel(
            name='SuccessNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_companies', models.IntegerField()),
                ('export_revenue', models.IntegerField()),
                ('export_destinations', models.IntegerField()),
                ('skilled_specialists', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Success Number',
                'verbose_name_plural': 'Success Numbers',
            },
        ),
        migrations.CreateModel(
            name='SpecialService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='special_services/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.specialcategories')),
            ],
            options={
                'verbose_name': 'Special Service',
                'verbose_name_plural': 'Special Services',
            },
        ),
    ]
