# Generated by Django 5.2.7 on 2025-10-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_specialcategories_successnumber_specialservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialservice',
            name='content',
            field=models.TextField(max_length=400),
        ),
    ]
