# Generated by Django 5.2.7 on 2025-10-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_specialservice_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='content_image',
            field=models.ImageField(default=1, upload_to='blog_content_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='main_image',
            field=models.ImageField(default=1, upload_to='blog_main_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialservice',
            name='content',
            field=models.CharField(max_length=400),
        ),
    ]
