# Generated by Django 5.2.7 on 2025-10-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_blog_options_remove_blog_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='education_images/')),
            ],
            options={
                'verbose_name': 'Education & Talent Development',
                'verbose_name_plural': 'Educations & Talent Developments',
            },
        ),
        migrations.CreateModel(
            name='InvestorProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='investor_programs/')),
            ],
            options={
                'verbose_name': 'Investor Program',
                'verbose_name_plural': 'Investor Programs',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employed_professionals', models.IntegerField()),
                ('companies', models.IntegerField()),
                ('professionals_count', models.IntegerField()),
                ('coverage', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_taxes', models.FloatField()),
                ('property_and_land_taxes', models.FloatField()),
                ('tax_on_dividends', models.FloatField()),
                ('billion_turnover_tax', models.FloatField()),
                ('social_tax', models.FloatField()),
                ('vat_on_imported_services', models.BooleanField()),
                ('personal_income_tax', models.FloatField()),
                ('value_added_tax', models.FloatField()),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxes',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(max_length=140),
        ),
    ]
