# Generated by Django 5.2.7 on 2025-11-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_education_investorprogram_statistics_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='specialservice',
            name='content',
            field=models.TextField(max_length=400),
        ),
    ]
